Problem 1-1

In [ ]:
import numpy as np
empty_array=np.empty((2,2))
print(empty_array)

[[0. 0.]
 [0. 0.]]


2

In [ ]:
import numpy as np
all_one=np.ones((4,2))
print(all_one)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


3

In [ ]:
import numpy as np
arr=np.full((3,2),3)
print(arr)

[[3 3]
 [3 3]
 [3 3]]


4

In [ ]:
import numpy as np
arr1=[[1,2],[2,3]]
arr=np.zeros_like((arr1))
print(arr)

[[0 0]
 [0 0]]


5

In [ ]:
import numpy as np
arr1=[[1,2],[2,3]]
arr=np.ones_like((arr1))
print(arr)

[[1 1]
 [1 1]]


6

In [ ]:
new_list = [1,2,3,4]
arr=np.array(new_list)
print(arr)

[1 2 3 4]


PROBLEM 2
1

In [ ]:
arr=np.arange(10,49)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


2

In [ ]:
arr=np.arange(0,9)
arr1=arr.reshape((3,3))
print(arr1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


3

In [ ]:
arr=np.eye(3,3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4

In [ ]:
import random as random
arr=np.random.random(30)
print(arr)
mean=np.mean(arr)
print("Mean is - ",mean)


[0.62874924 0.17617044 0.45119261 0.06955537 0.22928344 0.48609798
 0.29621884 0.86735556 0.2210408  0.02901617 0.35435835 0.90221466
 0.01650627 0.04359248 0.26726365 0.22871591 0.98579083 0.46749197
 0.96891918 0.07324887 0.96172703 0.03141921 0.88758031 0.28805083
 0.37602256 0.38546202 0.46176075 0.51246289 0.13589745 0.84432226]
Mean is -  0.42158293078207737


5

In [ ]:
arr=np.random.random((10,10))
arr1=np.min(arr)
arr2=np.max(arr)
print("Minimum value is - ",arr1)
print("Maximum value is - ",arr2)

Minimum value is -  0.0007720519715966878
Maximum value is -  0.9938461201626608


6

In [ ]:
arr=np.zeros(10)
arr[4]=1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7

In [2]:
arr = [1,2,0,0,4,0]
rev=arr[::-1]
print(rev)

[0, 4, 0, 0, 2, 1]


8

In [ ]:
n,m = 4, 4
arr = np.zeros((n,m))
arr[0, :] = 1
arr[-1, :] = 1
arr[:, 0] = 1
arr[:, -1] = 1
print(arr)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


9

In [ ]:
checkboard=np.ones((8,8))
checkboard[1::2, ::2]=0
checkboard[::2, 1::2]=0
print(checkboard)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


PROBLEM 3 1

In [ ]:
v = np.array([9,10])
w = np.array([11,12])
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
print(np.add(x,y))
print(np.add(v,w))
print(np.subtract(x,y))
print(np.subtract(v,w))
print((x,y)*3)
print((v,w)*2)
print(np.square(x))
print(np.square(y))
print(np.square(v))
print(np.square(w))
print(np.dot(v,w))
print(np.dot(x,v))
print(np.dot(x,y))
print(np.concatenate((x,y), axis=0))
v=v.reshape(2,1)
w=w.reshape(2,1)
print(np.concatenate((v,w), axis=1))
print(np.concatenate((x,v), axis =1))
#print(np.concatenate((x,v), axis=0))

[[ 6  8]
 [10 13]]
[20 22]
[[-4 -4]
 [-4 -3]]
[-2 -2]
(array([[1, 2],
       [3, 5]]), array([[5, 6],
       [7, 8]]), array([[1, 2],
       [3, 5]]), array([[5, 6],
       [7, 8]]), array([[1, 2],
       [3, 5]]), array([[5, 6],
       [7, 8]]))
(array([ 9, 10]), array([11, 12]), array([ 9, 10]), array([11, 12]))
[[ 1  4]
 [ 9 25]]
[[25 36]
 [49 64]]
[ 81 100]
[121 144]
219
[29 77]
[[19 22]
 [50 58]]
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 11]
 [10 12]]
[[ 1  2  9]
 [ 3  5 10]]


PROBLEM 4

In [ ]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
A_inverse=np.linalg.inv(A)
print(np.dot(A, A_inverse))
print(np.dot(A,B))
print(np.dot(B,A))
AB = np.dot(A,B)
at= np.transpose(A)
bt= np.transpose(B)
print(np.dot(at,bt))

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
[[23 13]
 [51 29]]
[[36 44]
 [13 16]]
[[36 13]
 [44 16]]


In [ ]:
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([-1, -3, 9])
A_inverse = np.linalg.inv(A)
X = np.dot(A_inverse, B)
print(X)

[ 2.  1. -2.]


In [ ]:
import timeit
list1 = list(range(1000000))
list2 = list(range(1000000))


In [ ]:
from timeit import timeit
def add_python(Z1, Z2):
  return [z1 + z2 for z1, z2 in zip(Z1, Z2)]
def add_numpy(Z1, Z2):
  return np.add(Z1, Z2)
Z1 = random.sample(range(1000000), 10000)
Z2 = random.sample(range(1000000), 10000)
python_time = timeit("add_python(Z1,Z2)", globals=globals(), number=100)
numpy_time = timeit("add_numpy(Z1,Z2)", globals=globals(), number=100)
print(f"Pure Python addition: {python_time:.2f} s per loop")
print(f"Numpy addition: {numpy_time:.2f} s per loop")

Pure Python addition: 0.07 s per loop
Numpy addition: 0.12 s per loop


In [ ]:
from timeit import timeit
def mul_python(Z1, Z2):
  return [z1 * z2 for z1, z2 in zip(Z1, Z2)]
def mul_numpy(Z1, Z2):
  return np.multiply(Z1, Z2)
Z1 = random.sample(range(1000000), 10000)
Z2 = random.sample(range(1000000), 10000)
python_time = timeit("mul_python(Z1,Z2)", globals=globals(), number=100)
numpy_time = timeit("mul_numpy(Z1,Z2)", globals=globals(), number=100)
print(f"Pure Python multiplication: {python_time:.2f} s per loop")
print(f"Numpy multiplication: {numpy_time:.2f} s per loop")

Pure Python multiplication: 0.09 s per loop
Numpy multiplication: 0.13 s per loop


In [ ]:
from timeit import timeit
def dot_python(Z1, Z2):
  return sum(z1 * z2 for z1, z2 in zip(Z1, Z2))
def dot_numpy(Z1, Z2):
  return np.dot(Z1, Z2)
Z1 = random.sample(range(1000000), 10000)
Z2 = random.sample(range(1000000), 10000)
python_time = timeit("dot_python(Z1,Z2)", globals=globals(), number=100)
numpy_time = timeit("dot_numpy(Z1,Z2)", globals=globals(), number=100)
print(f"Pure Python dot product: {python_time:.2f} s per loop")
print(f"Numpy dot product: {numpy_time:.2f} s per loop")

Pure Python dot product: 0.09 s per loop
Numpy dot product: 0.15 s per loop


In [ ]:
from timeit import timeit
matrix1 = np.random.random((1000, 1000))
matrix2 = np.random.random((1000, 1000))
list1 = matrix1.tolist()
list2 = matrix2.tolist()
def matrix_python(list1, list2):
  list2_T = list(zip(*list2))
  return [[sum(a*b for a,b in zip(list1_row,list2_col)) for list2_col in list2_T] for list1_row in list1]
def matrix_numpy(matrix1, matrix2):
  return np.matmul(matrix1, matrix2)
#Z1 = random.sample(range(1000000), 10000)
#Z2 = random.sample(range(1000000), 10000)
python_time = timeit("matrix_python(list1,list2)", globals=globals(), number=1)
numpy_time = timeit("matrix_numpy(matrix1,matrix2)", globals=globals(), number=1)
print(f"Pure Python matrix multiplication: {python_time:.2f} s per loop")
print(f"Numpy matrix multiplication: {numpy_time:.2f} s per loop")

Numpy matrix multiplication: 0.15 s per loop
